//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_method_type")]
pub enum AuthMethodType {
    #[sea_orm(string_value = "Email")]
    Email,
    #[sea_orm(string_value = "Password")]
    Password,
}
