//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: Option<String>,
    pub login_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub auth_methods: HasMany<super::auth_methods::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
